In [1]:
#create an array: use numpy.array([data],dtype) function
#arrays can be created by directly loading data. data can be in the for of list or tuple
import numpy as np

np_array = np.array([[0,1,2,3,4],
                    [5,6,7,8,9],
                    [10,11,12,13,14]])
np_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
np_array = np.array([
    (1,2,3),
    (4,5,6)
])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#initialize an array when the contents of an array may not be known in advance

#3x4 array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#create a 2x3x4 array of ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
#create an empty 2x3 array
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#Creating a 1D array of numbers from 10 to 30 in increments of 5
np.arange(10,30,5)

array([10, 15, 20, 25])

In [13]:
#Creating a 1D array of numbers from 0 to 2 in increments of 0.3
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [14]:
## Creating a 1D array of 9 numbers equally spaced from 0 to 2
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
#retrieve basic information about arrays
# get the number of axis
np_array.ndim

2

In [16]:
#get the dimension of array
np_array.shape

(2, 3)

In [17]:
#the total number of elements in array
np_array.size

6

In [18]:
#type of elements in array
np_array.dtype

dtype('int32')

In [20]:
#performing basic arithmatic on arrays
a = np.array([20,30,40,50])
b = np.array([1,2,3,4])
c = a - b
c

array([19, 28, 37, 46])

In [21]:
#perform scalar operations element wise
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [22]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [24]:
#operations are always performed element wise
d = a*b
d

array([ 20,  60, 120, 200])

In [26]:
#more quick and useful functions
a = np.array([20,30,40,50])
a.max()
a.min()
a.sum()

140

In [29]:
#use the axis parameter for multidimensional array
b = np.arange(12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = b.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b.sum() #sum of all elements

66

In [32]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [36]:
b.sum(axis=1)

array([ 6, 22, 38])

In [34]:
b.min(axis=1)

array([0, 4, 8])

In [35]:
b.min(axis=0)

array([0, 1, 2, 3])

In [37]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])