In [1]:
#create an array: use numpy.array([data],dtype) function
#arrays can be created by directly loading data. data can be in the for of list or tuple
import numpy as np

np_array = np.array([[0,1,2,3,4],
                    [5,6,7,8,9],
                    [10,11,12,13,14]])
np_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
np_array = np.array([
    (1,2,3),
    (4,5,6)
])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#initialize an array when the contents of an array may not be known in advance

#3x4 array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#create a 2x3x4 array of ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
#create an empty 2x3 array
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#Creating a 1D array of numbers from 10 to 30 in increments of 5
np.arange(10,30,5)

array([10, 15, 20, 25])

In [13]:
#Creating a 1D array of numbers from 0 to 2 in increments of 0.3
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [14]:
## Creating a 1D array of 9 numbers equally spaced from 0 to 2
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [15]:
#retrieve basic information about arrays
# get the number of axis
np_array.ndim

2

In [16]:
#get the dimension of array
np_array.shape

(2, 3)

In [17]:
#the total number of elements in array
np_array.size

6

In [ ]:
#type