In [1]:
#create an array: use numpy.array([data],dtype) function
#arrays can be created by directly loading data. data can be in the for of list or tuple
import numpy as np

np_array = np.array([[0,1,2,3,4],
                    [5,6,7,8,9],
                    [10,11,12,13,14]])
np_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
np_array = np.array([
    (1,2,3),
    (4,5,6)
])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
#initialize an array when the contents of an array may not be known in advance

#3x4 array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])